//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_İngilizce_Website.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_English_DatabaseEntities : DbContext
    {
        public MVC_English_DatabaseEntities()
            : base("name=MVC_English_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GirisTablosu> GirisTablosu { get; set; }
        public virtual DbSet<İletisimTablosu> İletisimTablosu { get; set; }
        public virtual DbSet<UygulamaTablosu> UygulamaTablosu { get; set; }
    }
}
